name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        uses: ./
        id: update
        with:
          version: 1.1.0
      - name: show
        run: git diff
