name: Swift

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  default:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        uses: ./
        id: update
        with:
          version: 1.1.0
      - name: show
        run: git diff

  projectPath:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        uses: ./
        id: update
        with:
          version: 1.1.0
          project-path: ./

      - name: show
        run: git diff

  versionPath:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        uses: ./
        id: update
        with:
          version-path: version.txt
      - name: show
        run: git diff

  output:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        uses: ./
        id: update
        with:
          version-path: version.txt
      - name: show
        run: |
          echo "${{ steps.update.outputs.version }}"
          echo "${{ steps.update.outputs.build-number }}"